name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Basic-1
      id: basic-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Basic-1
        setup-command: ''
        command: "./grade/basic-1.sh"
        timeout: 10
        max-score: 8
    - name: Complie
      id: complie
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Complie
        setup-command: ''
        command: gcc -g -Wall -c proxy.c;gcc -g -Wall -c csapp.c；gcc -g -Wall proxy.o
          csapp.o -o proxy -lpthread
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BASIC-1_RESULTS: "${{steps.basic-1.outputs.result}}"
        COMPLIE_RESULTS: "${{steps.complie.outputs.result}}"
      with:
        runners: basic-1,complie
